services:
  db:
    image: mysql:8.4
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: sync_wand
      MYSQL_USER: sync_wand
      MYSQL_PASSWORD: sync_wand_local_password
      MYSQL_ROOT_PASSWORD: root_local_password
    volumes:
      - ./mysql:/var/lib/mysql

  # Legacy MongoDB para recuperar datos locales si fuera necesario:
  # mongo:
  #   image: mongo:5
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGODB_DATABASE: sync-wand
  #   volumes:
  #     - ./mongo:/data/db
